/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.vista;

/**
 *
 * @author pc
 */
public class PresupuestoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PresupuestoJPanel
     */
    public PresupuestoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presupuesto_lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fecha_Presupuesto_lbl = new javax.swing.JLabel();
        fecha_Presupuesto_txf = new javax.swing.JTextField();
        nroTecnico_lbl = new javax.swing.JLabel();
        nroTecnico_txf = new javax.swing.JTextField();
        horasTrabajo_lbl = new javax.swing.JLabel();
        horasTrabajo_txf = new javax.swing.JTextField();
        componentes_lbl = new javax.swing.JLabel();
        componentes_jComboBox = new javax.swing.JComboBox<>();
        cantidad_lbl = new javax.swing.JLabel();
        iconMas_lbl = new javax.swing.JLabel();
        iconMenos_lbl = new javax.swing.JLabel();
        iconIngresar_lbl = new javax.swing.JLabel();
        listaComponentesSeleccionados_jScrollPane = new javax.swing.JScrollPane();
        listaComponentesSeleccionados_jList = new javax.swing.JList<>();
        descripcionBreve_lbl = new javax.swing.JLabel();
        descripcionTecnica_lbl = new javax.swing.JLabel();
        descripcionTecnica_jScrollPane = new javax.swing.JScrollPane();
        descripcionTecnica_jTextArea = new javax.swing.JTextArea();
        descripcionBreve_jScrollPane = new javax.swing.JScrollPane();
        descripcionBreve_jTextArea = new javax.swing.JTextArea();
        valorPresupuestado_lbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        presupuesto_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        presupuesto_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        presupuesto_lbl.setText("Presupuesto");

        jSeparator1.setBackground(new java.awt.Color(0, 102, 255));

        fecha_Presupuesto_lbl.setText("Fecha");

        fecha_Presupuesto_txf.setBorder(null);
        fecha_Presupuesto_txf.setEnabled(false);
        fecha_Presupuesto_txf.setOpaque(false);

        nroTecnico_lbl.setText("Nro Técnico");

        horasTrabajo_lbl.setText("Horas de Trabajo");

        componentes_lbl.setText("Componentes");

        componentes_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cantidad_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad_lbl.setText("0");
        cantidad_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        iconMas_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/plus-outline.png"))); // NOI18N

        iconMenos_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/minus-outline.png"))); // NOI18N

        iconIngresar_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons/tick-outline.png"))); // NOI18N

        listaComponentesSeleccionados_jList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        listaComponentesSeleccionados_jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nombre Cantidad", "item3 item4", "item5 item6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaComponentesSeleccionados_jScrollPane.setViewportView(listaComponentesSeleccionados_jList);

        descripcionBreve_lbl.setText("Descripción Breve ");

        descripcionTecnica_lbl.setText("Descripción Técnica");

        descripcionTecnica_jTextArea.setColumns(20);
        descripcionTecnica_jTextArea.setRows(5);
        descripcionTecnica_jScrollPane.setViewportView(descripcionTecnica_jTextArea);

        descripcionBreve_jTextArea.setColumns(20);
        descripcionBreve_jTextArea.setRows(5);
        descripcionBreve_jScrollPane.setViewportView(descripcionBreve_jTextArea);

        valorPresupuestado_lbl.setText("Valor Presupuestado");

        jTextField1.setEditable(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextField1.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(presupuesto_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(fecha_Presupuesto_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecha_Presupuesto_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descripcionBreve_lbl)
                        .addGap(248, 248, 248)
                        .addComponent(descripcionTecnica_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nroTecnico_lbl)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(componentes_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horasTrabajo_lbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nroTecnico_txf)
                            .addComponent(horasTrabajo_txf)
                            .addComponent(componentes_jComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconMas_lbl)
                        .addGap(4, 4, 4)
                        .addComponent(cantidad_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconMenos_lbl)
                        .addGap(10, 10, 10)
                        .addComponent(iconIngresar_lbl))
                    .addComponent(listaComponentesSeleccionados_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(descripcionBreve_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcionTecnica_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valorPresupuestado_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presupuesto_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_Presupuesto_lbl)
                    .addComponent(fecha_Presupuesto_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroTecnico_lbl)
                    .addComponent(nroTecnico_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horasTrabajo_lbl)
                    .addComponent(horasTrabajo_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(componentes_lbl)
                    .addComponent(componentes_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconMas_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconMenos_lbl)
                    .addComponent(iconIngresar_lbl))
                .addGap(18, 18, 18)
                .addComponent(listaComponentesSeleccionados_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionBreve_lbl)
                    .addComponent(descripcionTecnica_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionTecnica_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionBreve_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorPresupuestado_lbl)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidad_lbl;
    private javax.swing.JComboBox<String> componentes_jComboBox;
    private javax.swing.JLabel componentes_lbl;
    private javax.swing.JScrollPane descripcionBreve_jScrollPane;
    private javax.swing.JTextArea descripcionBreve_jTextArea;
    private javax.swing.JLabel descripcionBreve_lbl;
    private javax.swing.JScrollPane descripcionTecnica_jScrollPane;
    private javax.swing.JTextArea descripcionTecnica_jTextArea;
    private javax.swing.JLabel descripcionTecnica_lbl;
    private javax.swing.JLabel fecha_Presupuesto_lbl;
    private javax.swing.JTextField fecha_Presupuesto_txf;
    private javax.swing.JLabel horasTrabajo_lbl;
    private javax.swing.JTextField horasTrabajo_txf;
    private javax.swing.JLabel iconIngresar_lbl;
    private javax.swing.JLabel iconMas_lbl;
    private javax.swing.JLabel iconMenos_lbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> listaComponentesSeleccionados_jList;
    private javax.swing.JScrollPane listaComponentesSeleccionados_jScrollPane;
    private javax.swing.JLabel nroTecnico_lbl;
    private javax.swing.JTextField nroTecnico_txf;
    private javax.swing.JLabel presupuesto_lbl;
    private javax.swing.JLabel valorPresupuestado_lbl;
    // End of variables declaration//GEN-END:variables
}
